export const initialTodos = [
  { _id: 1, description: "Learn JS", isComplete: true },
  { _id: 2, description: "Learn HTML", isComplete: true },
  { _id: 3, description: "Learn CSS", isComplete: true },
  {
    _id: 4,
    description: "Build an HTML/CSS/JS mini-project",
    isComplete: true,
  },
  { _id: 5, description: "Learn the command line", isComplete: true },
  { _id: 6, description: "Learn Git", isComplete: true },
  { _id: 7, description: "Learn Node", isComplete: true },
  { _id: 8, description: "Learn React", isComplete: false },
  { _id: 9, description: "Build a Node/CLI mini-project", isComplete: false },
  { _id: 10, description: "Build a React mini-project", isComplete: false },
  { _id: 11, description: "Learn Next", isComplete: false },
  { _id: 12, description: "Onboard onto a full project", isComplete: false },
  { _id: 13, description: "Learn Express", isComplete: false },
  { _id: 14, description: "Learn MongoDB", isComplete: false },
];
